name: CI - Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Benötigt für Checkout
      security-events: write # Benötigt für das Hochladen von CodeQL SARIF Ergebnissen
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint
        continue-on-error: true


      - name: Check Formatting
        run: npm run format:check

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
